skeleton:
    angles:
        joints:

            left_back_ankle: [HindKneeLeft, BackAnkleLeft, HindPawLeft]
#            right_back_ankle: [HindKneeRight, BackAnkleRight, HindPawRight]
            snout_to_ears: [EarLeft, Snout, EarRight]


        references:
            full_body_tilt: [lshoulder, lmtp, mcorner]
            maze_corner_open_right: [mcorner_ol, mcorner_or, mcorner_cr]
    correlations:
        left_shoulder_knee : [lknee, lshoulder]
    distances:
        lef_shoulder_to_toe: [lshoulder, lmtp]
    elevations:
        left_hip: lhip
        right_hip: rhip
    
    
features:
    extraction_strategies.SampleFeatureExtractionStrategy:
        window_size: 1
        aggregation_method: sum
        marker_ids: [TailBase]
#    phase.PhasesAngle:
#        marker_ids: [left_back_ankle]
#        window_size: 1
#    joint_angles_dlc2kin.JointAnglesDLC:
#        window_size: 1
#        marker_id: [left_back_ankle]
#    joint_angles_dlc2kin.AngularVelocityDLC:
#        window_size: 3
    momentum_dlc2kin.AccelerationDLC:
        window_size: 3
        marker_ids: [TailBase]
#    momentum_dlc2kin.VelocityDLC:
#        window_size: 3
#        marker_ids: [TailBase]
    momentum_dlc2kin.SpeedDLC:
         window_size: 3

    #threshold_based_classification.Immobility:
    #     immobility_threshold: 1
    #     marker_id: [Snout, TailBase]



events:
    freezing_of_gait:
        get_frames_where_feature_of_marker_id_is_below_threshold: 
            marker_id: rknee
            feature: speed
            threshold: 5
        get_freezing_events: [(marker_id, center_of_gravity), (min_duration, 0.5)]
        get_predictions: [(model_path, path), (hyperparameters, dictionary_of_hyperparams)]