skeleton:
    angles:
        joints:
            # some naming mistakes were made during creation of the dlc networks
            left_back_ankle: [HindKneeLeft, BackAnkleLeft, HindPawLeft]
            right_back_ankle: [HindKneeRight, BackAngleRight, HindPawRight]
            left_wrist: [ ElbowLeft, WristLeft, FrontPawLeft ]
            right_wrist: [ ElbowRight, WristRight, FrontPawRight ]
            left_knee: [ HindKneeLeft, HindKneeLeft, BackAnkleLeft ]
            right_knee: [ HindKneeRight, HindKneeRight, BackAngleRight ]
            left_elbow: [ ShoulderLeft, ElbowLeft, FrontPawLeft ]
            right_elbow: [ ShoulderRight, ElbowRight, FrontPawRight ]
            left_hip: [ HipLeft, HindKneeLeft, BackAnkleLeft ]
            right_hip: [ HipRight, HindKneeRight, BackAnkleRight ]
            left_shoulder: [ ShoulderLeft, ElbowLeft, FrontPawLeft ]
            right_shoulder: [ ShoulderRight, ElbowRight, FrontPawRight ]

    references:
        full_body_tilt: [lshoulder, lmtp, mcorner]
        maze_corner_open_right: [mcorner_ol, mcorner_or, mcorner_cr]
    correlations:
        left_shoulder_knee : [lknee, lshoulder]
    distances:
        left_shoulder_to_paw: [ShoulderLeft, ForePawLeft]
        right_shoulder_to_paw: [ShoulderRight, ForePawRight]
        left_hip_to_paw: [HipLeft, HindPawLeft]
        right_hip_to_paw: [HipRight, HindPawRight]
        left_hip_to_shoulder: [HipLeft, ShoulderLeft]
        right_hip_to_shoulder: [HipRight, ShoulderRight]
        left_forepaw_to_hindpaw: [ForePawLeft, HindPawLeft]
        right_forepaw_to_hindpaw: [ForePawRight, HindPawRight]
        hindpaw_to_hindpaw: [HindPawLeft, HindPawRight]
        forepaw_to_forepaw: [ForePawLeft, ForePawRight]
        snout_to_tailbase: [Snout, TailBase]
        maze_corner_closed_right_to_open_right: [MazeCornerClosedRight, MazeCornerOpenRight]
        maze_corner_closed_left_to_open_left: [MazeCornerClosedLeft, MazeCornerOpenLeft]
        maze_corner_closed_right_to_closed_left: [MazeCornerClosedRight, MazeCornerClosedLeft]
        maze_corner_open_right_to_open_left: [MazeCornerOpenRight, MazeCornerOpenLeft]

    elevations:
        left_hip: lhip
        right_hip: rhip
    
features:
#    extraction_strategies.SampleFeatureExtractionStrategy:
#        window_size: 1
#        aggregation_method: sum
#        marker_ids: [TailBase]
#    distances.Distance:
#    joint_angles_dlc2kin.JointAnglesDLC:
#        window_size: 11
#        marker_ids: [left_back_ankle]
#    joint_angles_dlc2kin.AngularVelocityDLC:
#        window_size: 11
#        fps: 80
#        marker_ids: [left_back_ankle]
#    momentum_dlc2kin.AccelerationDLC:
#        window_size: 11
#        fps: 80
#    momentum_dlc2kin.VelocityDLC:
#        window_size: 11
#        fps: 80
    momentum_dlc2kin.SpeedDLC:
        window_size: 11
        fps: 80

    direction.Direction:
        "front_marker": Snout
        "back_marker": TailBase
        "axis": x

    threshold_based_classification.Immobility:
        # immobility is always calculated for the whole subject.
        # please specify which markers need to be immobile to classify the whole subject as immobile
        immobility_threshold: 10
        minimum_duration_immobility: 0.1
        fps: 80
        marker_ids: [TailBase, Snout]

    threshold_based_classification.Freezing:
        # immobility is always calculated for the whole subject.
        # please specify which markers need to be immobile to classify the whole subject as immobile
        "markers_for_freezing": [Snout, TailBase]
        "front_marker": Snout
        "minimum_duration_freezing": 0.5
        "fps": 80

#    threshold_based_classification.GaitDisruption:
#        "markers_for_gait_disruption": [TailBase],
#        "min_duration_movement_before": 0.5
#        "min_duration_immobility": 0.1
#        "fps": 80
#        "front_marker": Snout
#        marker_ids: [TailBase]

#    step_parsing.StepParsing:
#        smoothing: False
#        smoothing_window_size: 11
#        relative_height: 0.9
#        step_filter_freq: 4
#        prominence: 0.1
#        fps: 80
#        min_x_diff: 0.25
#        marker_ids: [ForePawLeft, ForePawRight, HindPawLeft, HindPawRight]

events:
    freezing_of_gait:
        get_frames_where_feature_of_marker_id_is_below_threshold: 
            marker_id: rknee
            feature: speed
            threshold: 5
        get_freezing_events: [(marker_id, center_of_gravity), (min_duration, 0.5)]
        get_predictions: [(model_path, path), (hyperparameters, dictionary_of_hyperparams)]