skeleton:
    joints:
        left_crest: [lshoulder, lcrest, lhip]
        left_hip: [lcrest, lhip, lknee]
        left_knee: [lhip, lknee, lankle]
        left_ankle: [lknee, lankle, lmtp]
        right_crest: [rshoulder, rcrest, rhip]
        right_hip: [rcrest, rhip, rknee]
        right_knee: [rhip, rknee, rankle]
        right_ankle: [rknee, rankle, rmtp]
        trunk_cross_l: [lshoulder, rcrest, lhip]
        trunk_cross_r: [rshoulder, lcrest, rhip]
    distances:
        lef_shoulder_to_toe: [lshoulder, lmtp]
    elevations:
        left_hip: lhip
        right_hip: rhip


features:
    features.marker_features.LinearSpeed:
        window_size: 1
        marker_ids: [rknee]

    features.joint_features.Angle:
        joint_ids: [left_crest, right_hip, trunk_cross_r]

