skeleton:
    angles:
        joints:
            left_hip: [lcrest, lhip, lknee]
            left_knee: [lhip, lknee, lankle]
            left_ankle: [lknee, lankle, lmtp]
            right_hip: [rcrest, rhip, rknee]
            right_knee: [rhip, rknee, rankle]
            right_ankle: [rknee, rankle, rmtp]
        references:
            full_body_tilt: [lshoulder, lmtp, mcorner]
            maze_corner_open_right: [mcorner_ol, mcorner_or, mcorner_cr]        
    distances:
        lef_shoulder_to_toe: [lshoulder, lmtp]
    elevations:
        left_hip: lhip
        right_hip: rhip
    
    
features:
    #extraction_strategies.SampleFeatureExtractionStrategy:
    #    window_size: 10
    #    marker_ids: [lshoulder]
    #phase.PhasesAngle:
    #    marker_ids: [left_knee]
    #momentum_dlc2kin.SpeedDLC:
    #    window_size: 3
    #    marker_ids: [lshoulder]
    joint_angles_dlc2kin.JointAnglesDLC:
        window_size: 3
        marker_ids: [left_hip]
    #    sliding_window_size: True
    #get_max_angle:
    #    marker_ids: [skeleton, angles, joints]
    


events:
    freezing_of_gait:
        get_frames_where_feature_of_marker_id_is_below_threshold: 
            marker_id: rknee
            feature: speed
            threshold: 5
        get_freezing_events: [(marker_id, center_of_gravity), (min_duration, 0.5)]
        get_predictions: [(model_path, path), (hyperparameters, dictionary_of_hyperparams)]