name: Publish to PyPI (tag v*)
on:
  push:
    tags: ["v*"]         
concurrency:
  group: pypi-publish-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Verify version matches tag
        run: |
              TAG="${GITHUB_REF_NAME#v}"
              PYVER=$(python setup.py --version) echo "tag=$TAG | setup.py version=$PYVER"[ "$TAG" = "$PYVER" ] || { echo "Tag v$TAG != package version $PYVER"; exit 1; }
      - name: Build
        run: |
          python -m pip install -U pip
          pip install build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with: { skip-existing: true }
